

export const dataFacturasContactos = [
    {
      id: '1',
      numero_cotizacion: 'CC000001',
      empresa_cotizacion: 'adasa',
      area_empresa: 'Energia',
      primer_nombre_consultor_empresa: 'Matias',
      apellido_paterno_consultor_empresa: 'Robles',
      apellido_materno_consultor_empresa: 'Morales',
      area_contacto: 'ITE',
      primer_nombre_contacto: 'Maritsa',
      apellido_paterno_contacto: 'Urbina',
      email_contacto: 'maritsa.urbina@enel.cl',
      monto_cotizacion: 190500000,
      fecha_creacion_cotizacion: '19-06-2026',
      fecha_envio_cotizacion: '01-07-2026',
      estado_cotizacion: 'Enviada'
    },
    {
      id: '2',
      numero_cotizacion: 'CC000002',
      empresa_cotizacion: 'Antucoya',
      area_empresa: 'Mineria',
      primer_nombre_consultor_empresa: 'Matias',
      apellido_paterno_consultor_empresa: 'Robles',
      apellido_materno_consultor_empresa: 'Morales',
      area_contacto: 'Adquisiciones',
      primer_nombre_contacto: 'Juan',
      apellido_paterno_contacto: 'Urbina',
      email_contacto: 'maritsa.urbina@enel.cl',
      monto_cotizacion: 190500000,
      fecha_creacion_cotizacion: '19-06-2026',
      fecha_envio_cotizacion: '20-06-2026',
      estado_cotizacion: 'Enviada'
    },
    {
      id: '3',
      numero_cotizacion: 'CC000003',
      empresa_cotizacion: 'Colbun',
      area_empresa: 'Energia',
      primer_nombre_consultor_empresa: 'Matias',
      apellido_paterno_consultor_empresa: 'Robles',
      apellido_materno_consultor_empresa: 'Morales',
      area_contacto: 'OTE',
      primer_nombre_contacto: 'Maritsa',
      apellido_paterno_contacto: 'Urbina',
      email_contacto: 'maritsa.urbina@enel.cl',
      monto_cotizacion: 190500000,
      fecha_creacion_cotizacion: '19-06-2026',
      fecha_envio_cotizacion: '19-06-2026',
      estado_cotizacion: 'Creada'
    },
    {
      id: '4',
      numero_cotizacion: 'CC000004',
      empresa_cotizacion: 'Cge',
      area_empresa: 'Energia',
      primer_nombre_consultor_empresa: 'Matias',
      apellido_paterno_consultor_empresa: 'Robles',
      apellido_materno_consultor_empresa: 'Morales',
      area_contacto: 'Adquisiciones',
      primer_nombre_contacto: 'Maritsa',
      apellido_paterno_contacto: 'Urbina',
      email_contacto: 'maritsa.urbina@enel.cl',
      monto_cotizacion: 190500000,
      fecha_creacion_cotizacion: '19-06-2026',
      fecha_envio_cotizacion: '30-06-2026',
      estado_cotizacion: 'Enviada'
    },
    {
      id: '5',
      numero_cotizacion: 'CC000005',
      empresa_cotizacion: 'Aguas Andina',
      area_empresa: 'Sanitaria',
      primer_nombre_consultor_empresa: 'Matias',
      apellido_paterno_consultor_empresa: 'Robles',
      apellido_materno_consultor_empresa: 'Morales',
      area_contacto: 'Compras',
      primer_nombre_contacto: 'Maritsa',
      apellido_paterno_contacto: 'Urbina',
      email_contacto: 'maritsa.urbina@enel.cl',
      monto_cotizacion: 190500000,
      fecha_creacion_cotizacion: '19-06-2026',
      fecha_envio_cotizacion: '05-07-2026',
      estado_cotizacion: 'Creada'
    },
    // {
    //   id: '6',
    //   icono_contacto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/nestjs.png',
    //   primer_nombre_contacto: 'Marcelo',
    //   apellido_paterno_contacto: 'Carcamo',
    //   apellido_materno_contacto: 'Salinas',
    //   area_contacto: 'Operaciones',
    //   cargo_contacto: 'Gerente',
    //   email_contacto: 'marceloAguas.aguasAndina.cl',
    //   telefono1_contacto: '+56927863984',
    //   telefono2_contacto: '+56979869708'
    // },
    // {
    //   id: '7',
    //   icono_contacto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/star.png',
    //   primer_nombre_contacto: 'Marcelo',
    //   apellido_paterno_contacto: 'Rivera',
    //   apellido_materno_contacto: 'Salinas',
    //   area_contacto: 'Operaciones',
    //   cargo_contacto: 'Gerente',
    //   email_contacto: 'marceloAguas.aguasAndina.cl',
    //   telefono1_contacto: '+56927863984',
    //   telefono2_contacto: '+56979869708'
    // },
    // {
    //   id: '8',
    //   icono_contacto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/logoPrincipal.png',
    //   primer_nombre_contacto: 'Camila',
    //   apellido_paterno_contacto: 'Tobar',
    //   apellido_materno_contacto: 'Salinas',
    //   area_contacto: 'Operaciones',
    //   cargo_contacto: 'Gerente',
    //   email_contacto: 'marceloAguas.aguasAndina.cl',
    //   telefono1_contacto: '+56927863984',
    //   telefono2_contacto: '+56979869708'
    // },
    
    // {
    //   id: '9',
    //   icono_contacto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/aws.png',
    //   primer_nombre_contacto: 'Carlos',
    //   apellido_paterno_contacto: 'Sanchez',
    //   apellido_materno_contacto: 'Salinas',
    //   area_contacto: 'Operaciones',
    //   cargo_contacto: 'Gerente',
    //   email_contacto: 'marceloAguas.aguasAndina.cl',
    //   telefono1_contacto: '+56927863984',
    //   telefono2_contacto: '+56979869708'
    // },
    // {
    //   id: '10',
    //   icono_contacto: 'https://roudev-s3-assets.s3.us-east-1.amazonaws.com/AssetsRoudev/Icons/azure.png',
    //   primer_nombre_contacto: 'Samanta',
    //   apellido_paterno_contacto: 'Escobar',
    //   apellido_materno_contacto: 'Torres',
    //   area_contacto: 'Operaciones',
    //   cargo_contacto: 'Gerente',
    //   email_contacto: 'marceloAguas.aguasAndina.cl',
    //   telefono1_contacto: '+56927863984',
    //   telefono2_contacto: '+56979869708'
    // },

    
]